{
 "title": "Go WebApp Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Processed Requests by Status Code and Method",
   "type": "graph",
   "description": "Shows the total number of requests processed by status code and method over time.",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_total) by (code, method)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS) by Status Code and Method",
   "type": "graph",
   "description": "Shows the number of requests processed every second by status code and method.",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(requests_total[1m])) by (code, method)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Request Duration (Median)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_duration_seconds_bucket{method=\"GET\"}[5m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Request Duration (75th Percentile)",
   "type": "gauge",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(request_duration_seconds_bucket{method=\"GET\"}[5m])) by (le))",
     "legendFormat": "75th Percentile"
    }
   ]
  },
  {
   "title": "Request Duration (95th percentile)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 9, "w": 6, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{method=\"GET\"}[5m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Request Duration (99th percentile)",
   "type": "gauge",
   "gridPos": { "x": 18, "y": 9, "w": 6, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{method=\"GET\"}[5m])) by (le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Total Errors Observed",
   "type": "graph",
   "description": "Shows the total number of errors observed over time.",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(requests_total{code=\"500\"})",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "In-flight HTTP Requests",
   "type": "graph",
   "description": "Shows the number of in-flight HTTP requests over time.",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "in_flight_requests", "legendFormat": "In-flight Requests" }
   ]
  },
  {
   "title": "Request Count Distribution",
   "type": "bargauge",
   "gridPos": { "x": 0, "y": 30, "w": 24, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(request_duration_seconds_bucket{method=\"GET\"}) by (le)",
     "legendFormat": "{{le}} seconds"
    }
   ]
  }
 ]
}